// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/proto/mq.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息结构体
type Msg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Msg) Reset() {
	*x = Msg{}
	mi := &file_api_proto_mq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_api_proto_mq_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Msg) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Msg) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// 键值对结构体
type Value struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // unix timestamp
	ExpireAt      int64                  `protobuf:"varint,3,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`    // unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_api_proto_mq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_api_proto_mq_proto_rawDescGZIP(), []int{1}
}

func (x *Value) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Value) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Value) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

// 创建队列请求
type CreateMqRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mq            string                 `protobuf:"bytes,1,opt,name=mq,proto3" json:"mq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMqRequest) Reset() {
	*x = CreateMqRequest{}
	mi := &file_api_proto_mq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMqRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMqRequest) ProtoMessage() {}

func (x *CreateMqRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMqRequest.ProtoReflect.Descriptor instead.
func (*CreateMqRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_mq_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMqRequest) GetMq() string {
	if x != nil {
		return x.Mq
	}
	return ""
}

// 创建队列响应
type CreateMqResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMqResponse) Reset() {
	*x = CreateMqResponse{}
	mi := &file_api_proto_mq_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMqResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMqResponse) ProtoMessage() {}

func (x *CreateMqResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mq_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMqResponse.ProtoReflect.Descriptor instead.
func (*CreateMqResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_mq_proto_rawDescGZIP(), []int{3}
}

func (x *CreateMqResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 删除队列请求
type DeleteMqRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mq            string                 `protobuf:"bytes,1,opt,name=mq,proto3" json:"mq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMqRequest) Reset() {
	*x = DeleteMqRequest{}
	mi := &file_api_proto_mq_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMqRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMqRequest) ProtoMessage() {}

func (x *DeleteMqRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mq_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMqRequest.ProtoReflect.Descriptor instead.
func (*DeleteMqRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_mq_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteMqRequest) GetMq() string {
	if x != nil {
		return x.Mq
	}
	return ""
}

// 删除队列响应
type DeleteMqResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMqResponse) Reset() {
	*x = DeleteMqResponse{}
	mi := &file_api_proto_mq_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMqResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMqResponse) ProtoMessage() {}

func (x *DeleteMqResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mq_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMqResponse.ProtoReflect.Descriptor instead.
func (*DeleteMqResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_mq_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteMqResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 推送消息请求
type PushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mq            string                 `protobuf:"bytes,1,opt,name=mq,proto3" json:"mq,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_api_proto_mq_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mq_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_mq_proto_rawDescGZIP(), []int{6}
}

func (x *PushRequest) GetMq() string {
	if x != nil {
		return x.Mq
	}
	return ""
}

func (x *PushRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 推送消息响应
type PushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResponse) Reset() {
	*x = PushResponse{}
	mi := &file_api_proto_mq_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse) ProtoMessage() {}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mq_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResponse.ProtoReflect.Descriptor instead.
func (*PushResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_mq_proto_rawDescGZIP(), []int{7}
}

func (x *PushResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PushResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 读取消息请求
type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mq            string                 `protobuf:"bytes,1,opt,name=mq,proto3" json:"mq,omitempty"`
	Num           int32                  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	Timeout       int64                  `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"` // 超时时间(秒)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_api_proto_mq_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mq_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_mq_proto_rawDescGZIP(), []int{8}
}

func (x *ReadRequest) GetMq() string {
	if x != nil {
		return x.Mq
	}
	return ""
}

func (x *ReadRequest) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *ReadRequest) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

// 读取消息响应
type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msgs          []*Msg                 `protobuf:"bytes,1,rep,name=msgs,proto3" json:"msgs,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_api_proto_mq_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mq_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_mq_proto_rawDescGZIP(), []int{9}
}

func (x *ReadResponse) GetMsgs() []*Msg {
	if x != nil {
		return x.Msgs
	}
	return nil
}

func (x *ReadResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 弹出消息请求
type PopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mq            string                 `protobuf:"bytes,1,opt,name=mq,proto3" json:"mq,omitempty"`
	Num           int32                  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PopRequest) Reset() {
	*x = PopRequest{}
	mi := &file_api_proto_mq_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopRequest) ProtoMessage() {}

func (x *PopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mq_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopRequest.ProtoReflect.Descriptor instead.
func (*PopRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_mq_proto_rawDescGZIP(), []int{10}
}

func (x *PopRequest) GetMq() string {
	if x != nil {
		return x.Mq
	}
	return ""
}

func (x *PopRequest) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

// 弹出消息响应
type PopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msgs          []*Msg                 `protobuf:"bytes,1,rep,name=msgs,proto3" json:"msgs,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PopResponse) Reset() {
	*x = PopResponse{}
	mi := &file_api_proto_mq_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopResponse) ProtoMessage() {}

func (x *PopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mq_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopResponse.ProtoReflect.Descriptor instead.
func (*PopResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_mq_proto_rawDescGZIP(), []int{11}
}

func (x *PopResponse) GetMsgs() []*Msg {
	if x != nil {
		return x.Msgs
	}
	return nil
}

func (x *PopResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 删除指定消息请求
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mq            string                 `protobuf:"bytes,1,opt,name=mq,proto3" json:"mq,omitempty"`
	Id            uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_proto_mq_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mq_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_mq_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteRequest) GetMq() string {
	if x != nil {
		return x.Mq
	}
	return ""
}

func (x *DeleteRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 删除指定消息响应
type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_proto_mq_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mq_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_mq_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 清空队列请求
type DropRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mq            string                 `protobuf:"bytes,1,opt,name=mq,proto3" json:"mq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropRequest) Reset() {
	*x = DropRequest{}
	mi := &file_api_proto_mq_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropRequest) ProtoMessage() {}

func (x *DropRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mq_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropRequest.ProtoReflect.Descriptor instead.
func (*DropRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_mq_proto_rawDescGZIP(), []int{14}
}

func (x *DropRequest) GetMq() string {
	if x != nil {
		return x.Mq
	}
	return ""
}

// 清空队列响应
type DropResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropResponse) Reset() {
	*x = DropResponse{}
	mi := &file_api_proto_mq_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropResponse) ProtoMessage() {}

func (x *DropResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mq_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropResponse.ProtoReflect.Descriptor instead.
func (*DropResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_mq_proto_rawDescGZIP(), []int{15}
}

func (x *DropResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 消息存档请求
type ActiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mq            string                 `protobuf:"bytes,1,opt,name=mq,proto3" json:"mq,omitempty"`
	Id            uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveRequest) Reset() {
	*x = ActiveRequest{}
	mi := &file_api_proto_mq_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveRequest) ProtoMessage() {}

func (x *ActiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mq_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveRequest.ProtoReflect.Descriptor instead.
func (*ActiveRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_mq_proto_rawDescGZIP(), []int{16}
}

func (x *ActiveRequest) GetMq() string {
	if x != nil {
		return x.Mq
	}
	return ""
}

func (x *ActiveRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 消息存档响应
type ActiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveResponse) Reset() {
	*x = ActiveResponse{}
	mi := &file_api_proto_mq_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveResponse) ProtoMessage() {}

func (x *ActiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mq_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveResponse.ProtoReflect.Descriptor instead.
func (*ActiveResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_mq_proto_rawDescGZIP(), []int{17}
}

func (x *ActiveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 获取队列长度请求
type LenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mq            string                 `protobuf:"bytes,1,opt,name=mq,proto3" json:"mq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LenRequest) Reset() {
	*x = LenRequest{}
	mi := &file_api_proto_mq_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LenRequest) ProtoMessage() {}

func (x *LenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mq_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LenRequest.ProtoReflect.Descriptor instead.
func (*LenRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_mq_proto_rawDescGZIP(), []int{18}
}

func (x *LenRequest) GetMq() string {
	if x != nil {
		return x.Mq
	}
	return ""
}

// 获取队列长度响应
type LenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Length        int32                  `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LenResponse) Reset() {
	*x = LenResponse{}
	mi := &file_api_proto_mq_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LenResponse) ProtoMessage() {}

func (x *LenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mq_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LenResponse.ProtoReflect.Descriptor instead.
func (*LenResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_mq_proto_rawDescGZIP(), []int{19}
}

func (x *LenResponse) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *LenResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 设置键值对请求
type SetKeyValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mq            string                 `protobuf:"bytes,1,opt,name=mq,proto3" json:"mq,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Expire        int64                  `protobuf:"varint,4,opt,name=expire,proto3" json:"expire,omitempty"` // 过期时间(秒)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetKeyValueRequest) Reset() {
	*x = SetKeyValueRequest{}
	mi := &file_api_proto_mq_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetKeyValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetKeyValueRequest) ProtoMessage() {}

func (x *SetKeyValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mq_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetKeyValueRequest.ProtoReflect.Descriptor instead.
func (*SetKeyValueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_mq_proto_rawDescGZIP(), []int{20}
}

func (x *SetKeyValueRequest) GetMq() string {
	if x != nil {
		return x.Mq
	}
	return ""
}

func (x *SetKeyValueRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetKeyValueRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetKeyValueRequest) GetExpire() int64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

// 设置键值对响应
type SetKeyValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetKeyValueResponse) Reset() {
	*x = SetKeyValueResponse{}
	mi := &file_api_proto_mq_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetKeyValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetKeyValueResponse) ProtoMessage() {}

func (x *SetKeyValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mq_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetKeyValueResponse.ProtoReflect.Descriptor instead.
func (*SetKeyValueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_mq_proto_rawDescGZIP(), []int{21}
}

func (x *SetKeyValueResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 获取键值对请求
type GetKeyValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mq            string                 `protobuf:"bytes,1,opt,name=mq,proto3" json:"mq,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyValueRequest) Reset() {
	*x = GetKeyValueRequest{}
	mi := &file_api_proto_mq_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyValueRequest) ProtoMessage() {}

func (x *GetKeyValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mq_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyValueRequest.ProtoReflect.Descriptor instead.
func (*GetKeyValueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_mq_proto_rawDescGZIP(), []int{22}
}

func (x *GetKeyValueRequest) GetMq() string {
	if x != nil {
		return x.Mq
	}
	return ""
}

func (x *GetKeyValueRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// 获取键值对响应
type GetKeyValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *Value                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyValueResponse) Reset() {
	*x = GetKeyValueResponse{}
	mi := &file_api_proto_mq_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyValueResponse) ProtoMessage() {}

func (x *GetKeyValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mq_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyValueResponse.ProtoReflect.Descriptor instead.
func (*GetKeyValueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_mq_proto_rawDescGZIP(), []int{23}
}

func (x *GetKeyValueResponse) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetKeyValueResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *GetKeyValueResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 删除键值对请求
type DeleteKeyValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mq            string                 `protobuf:"bytes,1,opt,name=mq,proto3" json:"mq,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeyValueRequest) Reset() {
	*x = DeleteKeyValueRequest{}
	mi := &file_api_proto_mq_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeyValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyValueRequest) ProtoMessage() {}

func (x *DeleteKeyValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mq_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyValueRequest.ProtoReflect.Descriptor instead.
func (*DeleteKeyValueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_mq_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteKeyValueRequest) GetMq() string {
	if x != nil {
		return x.Mq
	}
	return ""
}

func (x *DeleteKeyValueRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// 删除键值对响应
type DeleteKeyValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeyValueResponse) Reset() {
	*x = DeleteKeyValueResponse{}
	mi := &file_api_proto_mq_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeyValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyValueResponse) ProtoMessage() {}

func (x *DeleteKeyValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mq_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyValueResponse.ProtoReflect.Descriptor instead.
func (*DeleteKeyValueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_mq_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteKeyValueResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_proto_mq_proto protoreflect.FileDescriptor

const file_api_proto_mq_proto_rawDesc = "" +
	"\n" +
	"\x12api/proto/mq.proto\x12\x02mq\"H\n" +
	"\x03Msg\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\"Y\n" +
	"\x05Value\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\x03R\tupdatedAt\x12\x1b\n" +
	"\texpire_at\x18\x03 \x01(\x03R\bexpireAt\"!\n" +
	"\x0fCreateMqRequest\x12\x0e\n" +
	"\x02mq\x18\x01 \x01(\tR\x02mq\"(\n" +
	"\x10CreateMqResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"!\n" +
	"\x0fDeleteMqRequest\x12\x0e\n" +
	"\x02mq\x18\x01 \x01(\tR\x02mq\"(\n" +
	"\x10DeleteMqResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"/\n" +
	"\vPushRequest\x12\x0e\n" +
	"\x02mq\x18\x01 \x01(\tR\x02mq\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"4\n" +
	"\fPushResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"I\n" +
	"\vReadRequest\x12\x0e\n" +
	"\x02mq\x18\x01 \x01(\tR\x02mq\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x05R\x03num\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\x03R\atimeout\"A\n" +
	"\fReadResponse\x12\x1b\n" +
	"\x04msgs\x18\x01 \x03(\v2\a.mq.MsgR\x04msgs\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\".\n" +
	"\n" +
	"PopRequest\x12\x0e\n" +
	"\x02mq\x18\x01 \x01(\tR\x02mq\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x05R\x03num\"@\n" +
	"\vPopResponse\x12\x1b\n" +
	"\x04msgs\x18\x01 \x03(\v2\a.mq.MsgR\x04msgs\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"/\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02mq\x18\x01 \x01(\tR\x02mq\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\"&\n" +
	"\x0eDeleteResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x1d\n" +
	"\vDropRequest\x12\x0e\n" +
	"\x02mq\x18\x01 \x01(\tR\x02mq\"$\n" +
	"\fDropResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"/\n" +
	"\rActiveRequest\x12\x0e\n" +
	"\x02mq\x18\x01 \x01(\tR\x02mq\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\"&\n" +
	"\x0eActiveResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x1c\n" +
	"\n" +
	"LenRequest\x12\x0e\n" +
	"\x02mq\x18\x01 \x01(\tR\x02mq\";\n" +
	"\vLenResponse\x12\x16\n" +
	"\x06length\x18\x01 \x01(\x05R\x06length\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"d\n" +
	"\x12SetKeyValueRequest\x12\x0e\n" +
	"\x02mq\x18\x01 \x01(\tR\x02mq\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x16\n" +
	"\x06expire\x18\x04 \x01(\x03R\x06expire\"+\n" +
	"\x13SetKeyValueResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"6\n" +
	"\x12GetKeyValueRequest\x12\x0e\n" +
	"\x02mq\x18\x01 \x01(\tR\x02mq\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\\\n" +
	"\x13GetKeyValueResponse\x12\x1f\n" +
	"\x05value\x18\x01 \x01(\v2\t.mq.ValueR\x05value\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"9\n" +
	"\x15DeleteKeyValueRequest\x12\x0e\n" +
	"\x02mq\x18\x01 \x01(\tR\x02mq\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\".\n" +
	"\x16DeleteKeyValueResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error2\xee\x04\n" +
	"\x02MQ\x125\n" +
	"\bCreateMq\x12\x13.mq.CreateMqRequest\x1a\x14.mq.CreateMqResponse\x125\n" +
	"\bDeleteMq\x12\x13.mq.DeleteMqRequest\x1a\x14.mq.DeleteMqResponse\x12)\n" +
	"\x04Push\x12\x0f.mq.PushRequest\x1a\x10.mq.PushResponse\x12)\n" +
	"\x04Read\x12\x0f.mq.ReadRequest\x1a\x10.mq.ReadResponse\x12&\n" +
	"\x03Pop\x12\x0e.mq.PopRequest\x1a\x0f.mq.PopResponse\x12/\n" +
	"\x06Delete\x12\x11.mq.DeleteRequest\x1a\x12.mq.DeleteResponse\x12)\n" +
	"\x04Drop\x12\x0f.mq.DropRequest\x1a\x10.mq.DropResponse\x12/\n" +
	"\x06Active\x12\x11.mq.ActiveRequest\x1a\x12.mq.ActiveResponse\x12&\n" +
	"\x03Len\x12\x0e.mq.LenRequest\x1a\x0f.mq.LenResponse\x12>\n" +
	"\vSetKeyValue\x12\x16.mq.SetKeyValueRequest\x1a\x17.mq.SetKeyValueResponse\x12>\n" +
	"\vGetKeyValue\x12\x16.mq.GetKeyValueRequest\x1a\x17.mq.GetKeyValueResponse\x12G\n" +
	"\x0eDeleteKeyValue\x12\x19.mq.DeleteKeyValueRequest\x1a\x1a.mq.DeleteKeyValueResponseB\bZ\x06api/pbb\x06proto3"

var (
	file_api_proto_mq_proto_rawDescOnce sync.Once
	file_api_proto_mq_proto_rawDescData []byte
)

func file_api_proto_mq_proto_rawDescGZIP() []byte {
	file_api_proto_mq_proto_rawDescOnce.Do(func() {
		file_api_proto_mq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_mq_proto_rawDesc), len(file_api_proto_mq_proto_rawDesc)))
	})
	return file_api_proto_mq_proto_rawDescData
}

var file_api_proto_mq_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_api_proto_mq_proto_goTypes = []any{
	(*Msg)(nil),                    // 0: mq.Msg
	(*Value)(nil),                  // 1: mq.Value
	(*CreateMqRequest)(nil),        // 2: mq.CreateMqRequest
	(*CreateMqResponse)(nil),       // 3: mq.CreateMqResponse
	(*DeleteMqRequest)(nil),        // 4: mq.DeleteMqRequest
	(*DeleteMqResponse)(nil),       // 5: mq.DeleteMqResponse
	(*PushRequest)(nil),            // 6: mq.PushRequest
	(*PushResponse)(nil),           // 7: mq.PushResponse
	(*ReadRequest)(nil),            // 8: mq.ReadRequest
	(*ReadResponse)(nil),           // 9: mq.ReadResponse
	(*PopRequest)(nil),             // 10: mq.PopRequest
	(*PopResponse)(nil),            // 11: mq.PopResponse
	(*DeleteRequest)(nil),          // 12: mq.DeleteRequest
	(*DeleteResponse)(nil),         // 13: mq.DeleteResponse
	(*DropRequest)(nil),            // 14: mq.DropRequest
	(*DropResponse)(nil),           // 15: mq.DropResponse
	(*ActiveRequest)(nil),          // 16: mq.ActiveRequest
	(*ActiveResponse)(nil),         // 17: mq.ActiveResponse
	(*LenRequest)(nil),             // 18: mq.LenRequest
	(*LenResponse)(nil),            // 19: mq.LenResponse
	(*SetKeyValueRequest)(nil),     // 20: mq.SetKeyValueRequest
	(*SetKeyValueResponse)(nil),    // 21: mq.SetKeyValueResponse
	(*GetKeyValueRequest)(nil),     // 22: mq.GetKeyValueRequest
	(*GetKeyValueResponse)(nil),    // 23: mq.GetKeyValueResponse
	(*DeleteKeyValueRequest)(nil),  // 24: mq.DeleteKeyValueRequest
	(*DeleteKeyValueResponse)(nil), // 25: mq.DeleteKeyValueResponse
}
var file_api_proto_mq_proto_depIdxs = []int32{
	0,  // 0: mq.ReadResponse.msgs:type_name -> mq.Msg
	0,  // 1: mq.PopResponse.msgs:type_name -> mq.Msg
	1,  // 2: mq.GetKeyValueResponse.value:type_name -> mq.Value
	2,  // 3: mq.MQ.CreateMq:input_type -> mq.CreateMqRequest
	4,  // 4: mq.MQ.DeleteMq:input_type -> mq.DeleteMqRequest
	6,  // 5: mq.MQ.Push:input_type -> mq.PushRequest
	8,  // 6: mq.MQ.Read:input_type -> mq.ReadRequest
	10, // 7: mq.MQ.Pop:input_type -> mq.PopRequest
	12, // 8: mq.MQ.Delete:input_type -> mq.DeleteRequest
	14, // 9: mq.MQ.Drop:input_type -> mq.DropRequest
	16, // 10: mq.MQ.Active:input_type -> mq.ActiveRequest
	18, // 11: mq.MQ.Len:input_type -> mq.LenRequest
	20, // 12: mq.MQ.SetKeyValue:input_type -> mq.SetKeyValueRequest
	22, // 13: mq.MQ.GetKeyValue:input_type -> mq.GetKeyValueRequest
	24, // 14: mq.MQ.DeleteKeyValue:input_type -> mq.DeleteKeyValueRequest
	3,  // 15: mq.MQ.CreateMq:output_type -> mq.CreateMqResponse
	5,  // 16: mq.MQ.DeleteMq:output_type -> mq.DeleteMqResponse
	7,  // 17: mq.MQ.Push:output_type -> mq.PushResponse
	9,  // 18: mq.MQ.Read:output_type -> mq.ReadResponse
	11, // 19: mq.MQ.Pop:output_type -> mq.PopResponse
	13, // 20: mq.MQ.Delete:output_type -> mq.DeleteResponse
	15, // 21: mq.MQ.Drop:output_type -> mq.DropResponse
	17, // 22: mq.MQ.Active:output_type -> mq.ActiveResponse
	19, // 23: mq.MQ.Len:output_type -> mq.LenResponse
	21, // 24: mq.MQ.SetKeyValue:output_type -> mq.SetKeyValueResponse
	23, // 25: mq.MQ.GetKeyValue:output_type -> mq.GetKeyValueResponse
	25, // 26: mq.MQ.DeleteKeyValue:output_type -> mq.DeleteKeyValueResponse
	15, // [15:27] is the sub-list for method output_type
	3,  // [3:15] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_mq_proto_init() }
func file_api_proto_mq_proto_init() {
	if File_api_proto_mq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_mq_proto_rawDesc), len(file_api_proto_mq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_mq_proto_goTypes,
		DependencyIndexes: file_api_proto_mq_proto_depIdxs,
		MessageInfos:      file_api_proto_mq_proto_msgTypes,
	}.Build()
	File_api_proto_mq_proto = out.File
	file_api_proto_mq_proto_goTypes = nil
	file_api_proto_mq_proto_depIdxs = nil
}
