// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: api/proto/mq.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MQ_CreateMq_FullMethodName       = "/mq.MQ/CreateMq"
	MQ_DeleteMq_FullMethodName       = "/mq.MQ/DeleteMq"
	MQ_Push_FullMethodName           = "/mq.MQ/Push"
	MQ_Read_FullMethodName           = "/mq.MQ/Read"
	MQ_Pop_FullMethodName            = "/mq.MQ/Pop"
	MQ_Delete_FullMethodName         = "/mq.MQ/Delete"
	MQ_Drop_FullMethodName           = "/mq.MQ/Drop"
	MQ_Active_FullMethodName         = "/mq.MQ/Active"
	MQ_Len_FullMethodName            = "/mq.MQ/Len"
	MQ_SetKeyValue_FullMethodName    = "/mq.MQ/SetKeyValue"
	MQ_GetKeyValue_FullMethodName    = "/mq.MQ/GetKeyValue"
	MQ_DeleteKeyValue_FullMethodName = "/mq.MQ/DeleteKeyValue"
)

// MQClient is the client API for MQ service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MQ服务定义
type MQClient interface {
	// 创建队列
	CreateMq(ctx context.Context, in *CreateMqRequest, opts ...grpc.CallOption) (*CreateMqResponse, error)
	// 删除队列
	DeleteMq(ctx context.Context, in *DeleteMqRequest, opts ...grpc.CallOption) (*DeleteMqResponse, error)
	// 向队列里添加消息
	Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushResponse, error)
	// 读取指定条数消息，并设置超时时间
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	// 从队列中读取指定条数消息并删除
	Pop(ctx context.Context, in *PopRequest, opts ...grpc.CallOption) (*PopResponse, error)
	// 从队列中删除指定消息
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// 清空队列
	Drop(ctx context.Context, in *DropRequest, opts ...grpc.CallOption) (*DropResponse, error)
	// 将消息存档
	Active(ctx context.Context, in *ActiveRequest, opts ...grpc.CallOption) (*ActiveResponse, error)
	// 获取队列长度
	Len(ctx context.Context, in *LenRequest, opts ...grpc.CallOption) (*LenResponse, error)
	// 设置键值对
	SetKeyValue(ctx context.Context, in *SetKeyValueRequest, opts ...grpc.CallOption) (*SetKeyValueResponse, error)
	// 获取键值对
	GetKeyValue(ctx context.Context, in *GetKeyValueRequest, opts ...grpc.CallOption) (*GetKeyValueResponse, error)
	// 删除键值对
	DeleteKeyValue(ctx context.Context, in *DeleteKeyValueRequest, opts ...grpc.CallOption) (*DeleteKeyValueResponse, error)
}

type mQClient struct {
	cc grpc.ClientConnInterface
}

func NewMQClient(cc grpc.ClientConnInterface) MQClient {
	return &mQClient{cc}
}

func (c *mQClient) CreateMq(ctx context.Context, in *CreateMqRequest, opts ...grpc.CallOption) (*CreateMqResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMqResponse)
	err := c.cc.Invoke(ctx, MQ_CreateMq_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mQClient) DeleteMq(ctx context.Context, in *DeleteMqRequest, opts ...grpc.CallOption) (*DeleteMqResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMqResponse)
	err := c.cc.Invoke(ctx, MQ_DeleteMq_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mQClient) Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushResponse)
	err := c.cc.Invoke(ctx, MQ_Push_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mQClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, MQ_Read_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mQClient) Pop(ctx context.Context, in *PopRequest, opts ...grpc.CallOption) (*PopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PopResponse)
	err := c.cc.Invoke(ctx, MQ_Pop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mQClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, MQ_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mQClient) Drop(ctx context.Context, in *DropRequest, opts ...grpc.CallOption) (*DropResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DropResponse)
	err := c.cc.Invoke(ctx, MQ_Drop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mQClient) Active(ctx context.Context, in *ActiveRequest, opts ...grpc.CallOption) (*ActiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActiveResponse)
	err := c.cc.Invoke(ctx, MQ_Active_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mQClient) Len(ctx context.Context, in *LenRequest, opts ...grpc.CallOption) (*LenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LenResponse)
	err := c.cc.Invoke(ctx, MQ_Len_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mQClient) SetKeyValue(ctx context.Context, in *SetKeyValueRequest, opts ...grpc.CallOption) (*SetKeyValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetKeyValueResponse)
	err := c.cc.Invoke(ctx, MQ_SetKeyValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mQClient) GetKeyValue(ctx context.Context, in *GetKeyValueRequest, opts ...grpc.CallOption) (*GetKeyValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKeyValueResponse)
	err := c.cc.Invoke(ctx, MQ_GetKeyValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mQClient) DeleteKeyValue(ctx context.Context, in *DeleteKeyValueRequest, opts ...grpc.CallOption) (*DeleteKeyValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteKeyValueResponse)
	err := c.cc.Invoke(ctx, MQ_DeleteKeyValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MQServer is the server API for MQ service.
// All implementations must embed UnimplementedMQServer
// for forward compatibility.
//
// MQ服务定义
type MQServer interface {
	// 创建队列
	CreateMq(context.Context, *CreateMqRequest) (*CreateMqResponse, error)
	// 删除队列
	DeleteMq(context.Context, *DeleteMqRequest) (*DeleteMqResponse, error)
	// 向队列里添加消息
	Push(context.Context, *PushRequest) (*PushResponse, error)
	// 读取指定条数消息，并设置超时时间
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	// 从队列中读取指定条数消息并删除
	Pop(context.Context, *PopRequest) (*PopResponse, error)
	// 从队列中删除指定消息
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	// 清空队列
	Drop(context.Context, *DropRequest) (*DropResponse, error)
	// 将消息存档
	Active(context.Context, *ActiveRequest) (*ActiveResponse, error)
	// 获取队列长度
	Len(context.Context, *LenRequest) (*LenResponse, error)
	// 设置键值对
	SetKeyValue(context.Context, *SetKeyValueRequest) (*SetKeyValueResponse, error)
	// 获取键值对
	GetKeyValue(context.Context, *GetKeyValueRequest) (*GetKeyValueResponse, error)
	// 删除键值对
	DeleteKeyValue(context.Context, *DeleteKeyValueRequest) (*DeleteKeyValueResponse, error)
	mustEmbedUnimplementedMQServer()
}

// UnimplementedMQServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMQServer struct{}

func (UnimplementedMQServer) CreateMq(context.Context, *CreateMqRequest) (*CreateMqResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMq not implemented")
}
func (UnimplementedMQServer) DeleteMq(context.Context, *DeleteMqRequest) (*DeleteMqResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMq not implemented")
}
func (UnimplementedMQServer) Push(context.Context, *PushRequest) (*PushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedMQServer) Read(context.Context, *ReadRequest) (*ReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedMQServer) Pop(context.Context, *PopRequest) (*PopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pop not implemented")
}
func (UnimplementedMQServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedMQServer) Drop(context.Context, *DropRequest) (*DropResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Drop not implemented")
}
func (UnimplementedMQServer) Active(context.Context, *ActiveRequest) (*ActiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Active not implemented")
}
func (UnimplementedMQServer) Len(context.Context, *LenRequest) (*LenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Len not implemented")
}
func (UnimplementedMQServer) SetKeyValue(context.Context, *SetKeyValueRequest) (*SetKeyValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetKeyValue not implemented")
}
func (UnimplementedMQServer) GetKeyValue(context.Context, *GetKeyValueRequest) (*GetKeyValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeyValue not implemented")
}
func (UnimplementedMQServer) DeleteKeyValue(context.Context, *DeleteKeyValueRequest) (*DeleteKeyValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteKeyValue not implemented")
}
func (UnimplementedMQServer) mustEmbedUnimplementedMQServer() {}
func (UnimplementedMQServer) testEmbeddedByValue()            {}

// UnsafeMQServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MQServer will
// result in compilation errors.
type UnsafeMQServer interface {
	mustEmbedUnimplementedMQServer()
}

func RegisterMQServer(s grpc.ServiceRegistrar, srv MQServer) {
	// If the following call pancis, it indicates UnimplementedMQServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MQ_ServiceDesc, srv)
}

func _MQ_CreateMq_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMqRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MQServer).CreateMq(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MQ_CreateMq_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MQServer).CreateMq(ctx, req.(*CreateMqRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MQ_DeleteMq_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMqRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MQServer).DeleteMq(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MQ_DeleteMq_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MQServer).DeleteMq(ctx, req.(*DeleteMqRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MQ_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MQServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MQ_Push_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MQServer).Push(ctx, req.(*PushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MQ_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MQServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MQ_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MQServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MQ_Pop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MQServer).Pop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MQ_Pop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MQServer).Pop(ctx, req.(*PopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MQ_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MQServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MQ_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MQServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MQ_Drop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MQServer).Drop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MQ_Drop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MQServer).Drop(ctx, req.(*DropRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MQ_Active_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MQServer).Active(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MQ_Active_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MQServer).Active(ctx, req.(*ActiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MQ_Len_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MQServer).Len(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MQ_Len_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MQServer).Len(ctx, req.(*LenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MQ_SetKeyValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetKeyValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MQServer).SetKeyValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MQ_SetKeyValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MQServer).SetKeyValue(ctx, req.(*SetKeyValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MQ_GetKeyValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MQServer).GetKeyValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MQ_GetKeyValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MQServer).GetKeyValue(ctx, req.(*GetKeyValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MQ_DeleteKeyValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKeyValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MQServer).DeleteKeyValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MQ_DeleteKeyValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MQServer).DeleteKeyValue(ctx, req.(*DeleteKeyValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MQ_ServiceDesc is the grpc.ServiceDesc for MQ service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MQ_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mq.MQ",
	HandlerType: (*MQServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMq",
			Handler:    _MQ_CreateMq_Handler,
		},
		{
			MethodName: "DeleteMq",
			Handler:    _MQ_DeleteMq_Handler,
		},
		{
			MethodName: "Push",
			Handler:    _MQ_Push_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _MQ_Read_Handler,
		},
		{
			MethodName: "Pop",
			Handler:    _MQ_Pop_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _MQ_Delete_Handler,
		},
		{
			MethodName: "Drop",
			Handler:    _MQ_Drop_Handler,
		},
		{
			MethodName: "Active",
			Handler:    _MQ_Active_Handler,
		},
		{
			MethodName: "Len",
			Handler:    _MQ_Len_Handler,
		},
		{
			MethodName: "SetKeyValue",
			Handler:    _MQ_SetKeyValue_Handler,
		},
		{
			MethodName: "GetKeyValue",
			Handler:    _MQ_GetKeyValue_Handler,
		},
		{
			MethodName: "DeleteKeyValue",
			Handler:    _MQ_DeleteKeyValue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/mq.proto",
}
